TOP=../..

include $(TOP)/configure/CONFIG
#========================================
#  ADD MACRO DEFINITIONS AFTER THIS LINE

# Install .dbd and .db files
DB_INSTALLS += $(TOP)/capaNCDT6200Sup/Db/capaNCDT6200.proto
DB += xxCapaNCDT6200.vdb
DB += xxCapaMeas.vdb
DB += xxHydrostaticConfig.vdb
DB += xxHydrostaticMeas.vdb
DB += $(ASYN)/db/asynRecord.db

#========================================
include $(TOP)/configure/RULES
